baseURL = "https://cying.org/"
languageCode = "en-us"
title = "Nightingale "

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false       # 使用 CSS 类名，方便自定义样式
    style = "monokai"       # 设置代码高亮主题（可选：monokai、dracula、github 等）
    lineNumbers = true      # 显示行号
    lineNumbersInTable = true # 行号显示在表格中
    guessSyntax = true      # 自动猜测代码语言

[module]
  [[module.imports]]
    path = "github.com/person-c/Nothing" 